# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basicPercentage', models.FloatField(default=35)),
                ('hraPercentage', models.FloatField(default=40)),
                ('conveyanceAllowance', models.IntegerField(default=1600)),
                ('specialAllowance', models.IntegerField(default=0)),
                ('proffesionalTax', models.IntegerField(default=200)),
                ('incomeTax', models.IntegerField(default=0)),
                ('lossOfPay', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('grossEarnings', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('grossDeductions', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('totalDays', models.IntegerField(default=31)),
                ('weeklyoff', models.IntegerField(default=10)),
                ('paidDays', models.IntegerField(default=22)),
                ('net_salary', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
            ],
        ),
    ]
