# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 05:59
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.IntegerField(blank=True, choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent')])),
                ('leave_type', models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=15)),
                ('isHalfDay', models.BooleanField()),
                ('isWorkFromHome', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format :'+999999999'. ", regex='^\\+?1?\\d{9,15}$')])),
                ('alter_Contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format :'+999999999'. ", regex='^\\+?1?\\d{9,15}$')])),
                ('emailid', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Select', max_length=1)),
                ('Dob', models.DateField()),
                ('profile_pic', models.ImageField(default='None/no-img.jpg', upload_to='payroll')),
                ('tax_status', models.CharField(choices=[('NRI', 'NRI'), ('RESIDENT', 'Resident'), ('EXPAT', 'Expat')], default='None', max_length=8)),
                ('privilegeleave', models.IntegerField(default=14)),
                ('casualleave', models.IntegerField(default=10)),
                ('joiningDate', models.DateField(blank=True, null=True)),
                ('jobType', models.CharField(blank=True, max_length=15)),
                ('jobLocation', models.CharField(blank=True, max_length=15)),
                ('confirmationPeriod', models.IntegerField(blank=True, default=2)),
                ('department', models.CharField(blank=True, max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basicPercentage', models.FloatField(default=35)),
                ('hraPercentage', models.FloatField(default=40)),
                ('conveyanceAllowance', models.IntegerField(default=1600)),
                ('specialAllowance', models.IntegerField(blank=True, default=0)),
                ('proffesionalTax', models.IntegerField(default=200)),
                ('incomeTax', models.IntegerField(default=0)),
                ('lossOfPay', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('grossEarnings', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('grossDeductions', models.DecimalField(decimal_places=2, default=Decimal('0.00000'), max_digits=5)),
                ('totalDays', models.IntegerField(default=31)),
                ('weeklyoff', models.IntegerField(default=10)),
                ('paidDays', models.IntegerField(default=22)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
    ]
