# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 04:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic_percentage', models.FloatField(default=35)),
                ('basic_amount', models.FloatField(default=0)),
                ('hra_amount', models.FloatField(default=0)),
                ('hra_percentage', models.FloatField(default=40)),
                ('conveyance_allowance', models.IntegerField(default=1600)),
                ('special_allowance', models.IntegerField(default=0)),
                ('proffessional_tax', models.IntegerField(default=200)),
                ('income_tax', models.IntegerField(default=0)),
                ('loss_of_pay', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('gross_earning', models.DecimalField(decimal_places=2, default=Decimal('0.000'), max_digits=10)),
                ('gross_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_days', models.IntegerField(default=25)),
                ('weekly_off', models.IntegerField(default=8)),
                ('paid_days', models.IntegerField(default=22)),
                ('net_salary', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Employee')),
            ],
        ),
    ]
