# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='aadhar',
        ),
    ]
