# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobLocation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_status',
            field=models.CharField(choices=[('NRI', 'NRI'), ('RESIDENT', 'Resident'), ('EXPAT', 'Expat')], default='None', max_length=15),
        ),
    ]
