# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180427_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='weekly_off',
            new_name='weekend',
        ),
        migrations.AddField(
            model_name='salary',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='public_holidays',
            field=models.IntegerField(default=0),
        ),
    ]
