# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180309_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='None/no-img.jpeg', upload_to='payroll'),
        ),
    ]
