# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_employee_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
