# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180310_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='job_location',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='jobType',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='joiningDate',
            new_name='joining_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='confirmationPeriod',
            new_name='probation_period',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isHalfDay',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isWorkFromHome',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='casualleave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='jobLocation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='privilegeleave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
