# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180228_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='auth.user'),
        ),
    ]
