# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180312_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=17)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Department_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('privilege_leave', models.IntegerField(default=0)),
                ('casual_leave', models.IntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Designation_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_leave', models.IntegerField(default=0)),
                ('casual_leave', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Salary_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic_percentage', models.FloatField(default=35)),
                ('hra_percentage', models.FloatField(default=40)),
                ('conveyance_allowance', models.IntegerField(default=1600)),
                ('special_allowance', models.IntegerField(blank=True, default=0)),
                ('proffesional_tax', models.IntegerField(default=200)),
                ('income_tax', models.IntegerField(default=0)),
                ('loss_of_pay', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('gross_deductions', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('total_days', models.IntegerField(default=0)),
                ('weekly_off', models.IntegerField(default=0)),
                ('paid_days', models.IntegerField(default=0)),
                ('net_salary', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tax_status',
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='salary_history',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Salary'),
        ),
        migrations.AddField(
            model_name='leave_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='job_type_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='job_type_history',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Job_Type'),
        ),
        migrations.AddField(
            model_name='designation_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
        migrations.AddField(
            model_name='department_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
    ]
