# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20180228_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='model_pic',
            field=models.ImageField(default='payroll/pic_folder/None/no-img.jpg', upload_to='payroll/pic_folder/'),
        ),
    ]
