# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20180301_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='model_pic',
            field=models.ImageField(default='None/no-img.jpg', upload_to='pic_folder'),
        ),
    ]
