# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20180531_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month_year',
            field=models.DateField(),
        ),
    ]
