# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20180301_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='model_pic',
            new_name='profile_pic',
        ),
    ]
