# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_salary_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month_year',
            field=models.DateField(blank=True),
        ),
    ]
