# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20180301_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.CharField(choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent'), (1, 'WorkFromHome')], max_length=12)),
                ('leave_type', models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=1)),
                ('privilege_leave', models.BooleanField()),
                ('casual_leave', models.BooleanField()),
            ],
        ),
    ]
