# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent'), (1, 'WorkFromHome')], max_length=12),
        ),
    ]
