# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20180303_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='None/no-img.jpg', upload_to='payroll'),
        ),
    ]
