# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20180305_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='casualleave',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmationPeriod',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='jobLocation',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='jobType',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='joiningDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='privilegeleave',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent'), (1, 'WorkFromHome')]),
        ),
    ]
