# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20180305_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
