# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=6556, max_digits=10),
            preserve_default=False,
        ),
    ]
