# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180409_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='company',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
