# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180409_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_type',
            name='worktype',
            field=models.CharField(choices=[('SH', 'Saturday Halfday'), ('SW', 'Saturday Working'), ('SSH', 'Saturday-Sunday Holiday'), ('WFH', 'Work From Home'), ('HD', 'Halfday')], max_length=200),
        ),
    ]
