# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:25
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('payroll', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format :'+999999999'. ", regex='^\\+?1?\\d{9,15}$')])),
                ('alter_Contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format :'+999999999'. ", regex='^\\+?1?\\d{9,15}$')])),
                ('emailid', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Select', max_length=20)),
                ('Dob', models.DateField()),
                ('profile_pic', models.ImageField(default='None/no-img.jpeg', upload_to='payroll')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=15)),
                ('job_location', models.CharField(blank=True, max_length=50)),
                ('probation_period', models.IntegerField(blank=True, default=2)),
                ('salary', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_leave', models.IntegerField(default=0)),
                ('casual_leave', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic_percentage', models.FloatField(default=35)),
                ('hra_percentage', models.FloatField(default=40)),
                ('conveyance_allowance', models.IntegerField(default=1600)),
                ('special_allowance', models.IntegerField(default=0)),
                ('proffesional_tax', models.IntegerField(default=200)),
                ('income_tax', models.IntegerField(default=0)),
                ('loss_of_pay', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('gross_deductions', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('total_days', models.IntegerField(default=0)),
                ('weekly_off', models.IntegerField(default=0)),
                ('paid_days', models.IntegerField(default=0)),
                ('net_salary', models.DecimalField(decimal_places=7, default=Decimal('0.000'), max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Employee')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Salary')),
            ],
        ),
        migrations.AddField(
            model_name='designation_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
        ),
        migrations.AddField(
            model_name='department_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
        ),
    ]
