# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 10:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_history',
            name='casual_leave',
        ),
        migrations.RemoveField(
            model_name='leave_history',
            name='privilege_leave',
        ),
        migrations.AddField(
            model_name='leave_history',
            name='leave_type',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='leave_history',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Work_Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.000'), max_digits=19),
        ),
    ]
