# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 10:55
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180313_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.000'), max_digits=12),
        ),
    ]
