# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180409_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Dob',
            field=models.DateField(null=True),
        ),
    ]
