# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180423_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='None/no-img.jpeg', upload_to='payroll'),
        ),
    ]
