# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='None/no-img.jpeg', upload_to='payroll'),
        ),
    ]
