# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_employee_office_emailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_history',
            old_name='special_allowance',
            new_name='bonus',
        ),
    ]
