# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180608_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_history',
            name='bonus',
        ),
    ]
