# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 06:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_salary_history_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_increment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('effective_from', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Employee')),
            ],
        ),
    ]
