# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 09:37
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(upload_to='payroll'),
        ),
        migrations.AlterField(
            model_name='salary_increment',
            name='effective_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='salary_increment',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
