# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180625_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='None/no-img.jpeg', upload_to='payroll'),
        ),
    ]
