# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180625_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emailid',
        ),
    ]
