# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180626_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='probation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
