# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('mark', models.IntegerField(blank=True, choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent')])),
                ('leave_type', models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_type', models.CharField(max_length=200)),
            ],
        ),
    ]
