# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180409_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='cl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remCasualLeave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remPrivilegeLeave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=15),
        ),
    ]
