# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180415_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='Remark',
            field=models.CharField(blank=True, choices=[('S', 'Sanctioned'), ('NS', 'Not Sanctioned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
