# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180415_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_application',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='leave_type',
            field=models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=200),
        ),
    ]
