# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180415_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
