# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20180503_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lop',
        ),
    ]
