# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_lop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='pl',
            field=models.IntegerField(default=0),
        ),
    ]
