# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20180503_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cl',
            field=models.IntegerField(default=0),
        ),
    ]
