# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20180509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[(1, 'Present'), (0.5, 'Halfday'), (0, 'Absent')]),
        ),
    ]
